_gradient_huggingface: &_gradient_huggingface
  origin: https://github.com/graphcore/Gradient-HuggingFace.git
  ref: main


_common_target_repository: &_common_target_repository
    origin: notebooks/
    ref: null

dolly:
  source:
    paths:
    - path: dolly2-instruction-following/
    - path: LICENSE.md
    excludes:
    - path: dolly2-instruction-following/OpenAssistant-Pythia-12B-Chatbot.ipynb
    repository:
      <<: *_gradient_huggingface
      prefix: dolly2-instruction-following/
  target:
    renames:
      ./LICENSE.md: ./LICENSE
    repository:
      <<: *_common_target_repository
      prefix: ./

