_gradient_huggingface: &_gradient_huggingface
  origin: https://github.com/graphcore/Gradient-HuggingFace.git
  ref: main


_common_target_repository: &_common_target_repository
    origin: notebooks/
    ref: null

dolly:
  source:
    paths:
    - path: dolly-instruction-following/
    repository:
      <<: *_gradient_huggingface
      prefix: dolly-instruction-following/
  target:
    repository:
      <<: *_common_target_repository
      prefix: ./

