_gradient_huggingface: &_gradient_huggingface
  origin: https://github.com/graphcore/Gradient-HuggingFace.git
  ref: main


_common_target_repository: &_common_target_repository
    origin: notebooks/
    ref: null

dolly:
  source:
    paths:
    - expression: '*'
      path: dolly-instruction-following/Dolly2-an-OSS-instruction-LLM.ipynb
      recursive: true
    repository:
      <<: *_gradient_huggingface
      prefix: notebooks/
  target:
    renames:
      ./Dolly2-an-OSS-instruction-LLM.ipynb: ./dolly-ipu.ipynb
    repository:
      <<: *_common_target_repository
      prefix: ./

